Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

